### ISSUE TITLE
TR1_Task1: CodeSpike: Explore Database tools for the website

### ISSUE THREAD

**Issue by adrialfonso** [UB-ES-2024-A2/website_project_a2#10]

**Comment by Albert-23M** [comment]
Buenas, comento que el code spike ha sido investigado y una solución ha sido dada. Podemos usar un servidor cloud, proporcionado por Clever Server, usando una base de datos MySQL. He hecho pruebas de crear tablas desde python conectándome al servidor, y las pruebas han salido bien. Lo comentaremos en la reunión, ya que creo que es una herramienta que nos puede venir bien.
