### ISSUE TITLE
US3.2_Task1: Testing -> search bar (users)

### ISSUE THREAD

**Issue by adrialfonso** [UB-ES-2024-A2/website_project_a2#28]
## Description
*Explanation of the test to be created. Describe what functionality the test will cover and the expected outcomes.*

*Example: Create unit tests for the user registration endpoint to ensure that it correctly handles valid and invalid user input, including edge cases.*

## Checklist
- **Test Cases**:  
  *List the specific scenarios that will be tested, including both positive and negative cases. And the outcomes*
  - *Test Case 1*: Validate successful user registration with all required fields filled correctly.
  - *Test Case 2*: Validate error response when attempting to register with an existing email.
  - *Test Case 3*: Validate error response when the password does not meet complexity requirements.
  - *Test Case 4*: Validate response when required fields are missing.

- **Static testing**:  
  *Specify the static testing done.*
  - *Test Case 1*: Tested creating multiple users with the same email. Outcome. 

- **Setup Requirements**:  
  *Describe any setup required before tests can be run, such as seeding the database or mocking services.*
  - Example: Seed the test database with user data for integration tests.

**Comment by Albert-23M** [comment]
Branch for this issue has been created (task/US3.2_Task1-create-test-for-searchbar-users)
